\connect ShopDemoOrders

GRANT ALL ON SCHEMA public TO "ShopDemo";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "ShopDemo";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "ShopDemo";
