apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopdemo-orders
  namespace: shopdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopdemo-orders
  template:
    metadata:
      labels:
        app: shopdemo-orders
    spec:
      containers:
        - name: orders-api
          image: shopdemo-orders:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: PG_ORDERS_CONN
            - name: InventoryApi__BaseUrl
              value: "http://shopdemo-inventory:8080"
            - name: EventHubs__Enabled
              value: "true"
            - name: EventHubs__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: EVENT_HUBS_CONNECTION_STRING
            - name: EventHubs__EventHubName
              value: shopdemo-events
