apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shopdemo-postgres
  namespace: shopdemo
spec:
  serviceName: shopdemo-postgres
  replicas: 1
  selector:
    matchLabels:
      app: shopdemo-postgres
  template:
    metadata:
      labels:
        app: shopdemo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "ShopDemo"]
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: init-script
          configMap:
            name: shopdemo-postgres-init
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
