flowchart TB
  subgraph API["API / Presentacion"]
    CTRL[Controllers<br/>Catalog/Orders]
  end
  subgraph APP["Application"]
    CMD[Commands / Queries<br/>MediatR Handlers]
    VAL[FluentValidation]
  end
  subgraph DOM["Domain"]
    AGG[Aggregates<br/>Value Objects<br/>Domain Events]
  end
  subgraph INF["Infrastructure"]
    EF[EF Core DbContext]
    EH[Event Hubs Publisher]
    HTTP[HttpClient Inventory]
  end
  API --> APP
  APP --> DOM
  INF --> APP
  INF -.->|implementa| DOM
