flowchart LR
  subgraph DRIVING["Adaptadores driven (entrada)"]
    REST[Inventory API<br/>Controllers]
  end
  subgraph CORE["Nucleo hexagonal"]
    UC[Casos de uso<br/>IStockService]
    PORT[Inbound Ports]
    DOM[Domain Stock]
  end
  subgraph DRIVEN["Adaptadores driving (salida)"]
    REPO[EfStockRepository]
    EH[EventHubPublisher]
  end
  REST --> PORT
  PORT --> UC
  UC --> DOM
  UC --> REPO
  UC --> EH
