sequenceDiagram
  participant Postman
  participant C as Catalog :8001
  participant I as Inventory :8003
  participant O as Orders :8002
  participant EH as Event Hubs
  participant A as Analytics :8004

  Postman->>C: POST /api/products
  C-->>Postman: productId
  alt Event Hubs ON
    C->>EH: ProductCreatedDomainEvent
    EH->>I: consumer inventory-service
    I->>I: auto stock
    EH->>A: consumer analytics-service
  else Event Hubs OFF
    Postman->>I: POST /api/inventory/stock
  end
  Postman->>O: POST /api/orders
  Postman->>O: POST confirm
  O->>I: POST /reservations
