// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopDemo.Inventory.Infrastructure.Adapters.Persistence;

#nullable disable

namespace ShopDemo.Inventory.Infrastructure.Adapters.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260617012813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopDemo.Inventory.Domain.Aggregates.StockEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("product_name");

                    b.HasKey("Id");

                    b.ToTable("stock_entries", (string)null);
                });

            modelBuilder.Entity("ShopDemo.Inventory.Domain.Aggregates.StockEntry", b =>
                {
                    b.OwnsOne("ShopDemo.Inventory.Domain.ValueObjects.StockQuantity", "AvailableUnits", b1 =>
                        {
                            b1.Property<Guid>("StockEntryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("available_units");

                            b1.HasKey("StockEntryId");

                            b1.ToTable("stock_entries");

                            b1.WithOwner()
                                .HasForeignKey("StockEntryId");
                        });

                    b.Navigation("AvailableUnits")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
