apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopdemo-orders
  namespace: shopdemo
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: shopdemo-orders
  template:
    metadata:
      labels:
        app: shopdemo-orders
    spec:
      containers:
        - name: orders-api
          image: acrshopdemolab01.azurecr.io/shopdemo-orders:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: PG_ORDERS_CONN
            - name: InventoryApi__BaseUrl
              value: "http://shopdemo-inventory:8080"
            - name: EventHubs__Enabled
              value: "true"
            - name: EventHubs__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: shopdemo-secrets
                  key: EVENT_HUBS_CONNECTION_STRING
            - name: EventHubs__EventHubName
              value: shopdemo-events
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /alive
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
